/* tslint:disable */
/* eslint-disable */
/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/documents-api';
export * from './api/employee-api';
export * from './api/integrations-api';
export * from './api/kit-days-api';
export * from './api/leave-management-api';
export * from './api/offboarding-api';
export * from './api/onboarding-api';
export * from './api/performance-api';
export * from './api/policies-api';
export * from './api/positions-api';
export * from './api/recruitment-api';
export * from './api/teams-api';
export * from './api/terminations-reasons-api';
export * from './api/timesheets-api';

