/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  DocumentsApi,
  EmployeeApi,
  IntegrationsApi,
  KitDaysApi,
  LeaveManagementApi,
  OffboardingApi,
  OnboardingApi,
  PerformanceApi,
  PoliciesApi,
  PositionsApi,
  RecruitmentApi,
  TeamsApi,
  TerminationsReasonsApi,
  TimesheetsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { SageCustom } from "./client-custom";

export class Sage extends SageCustom {
  readonly documents: DocumentsApi;
  readonly employee: EmployeeApi;
  readonly integrations: IntegrationsApi;
  readonly kitDays: KitDaysApi;
  readonly leaveManagement: LeaveManagementApi;
  readonly offboarding: OffboardingApi;
  readonly onboarding: OnboardingApi;
  readonly performance: PerformanceApi;
  readonly policies: PoliciesApi;
  readonly positions: PositionsApi;
  readonly recruitment: RecruitmentApi;
  readonly teams: TeamsApi;
  readonly terminationsReasons: TerminationsReasonsApi;
  readonly timesheets: TimesheetsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.documents = new DocumentsApi(configuration);
    this.employee = new EmployeeApi(configuration);
    this.integrations = new IntegrationsApi(configuration);
    this.kitDays = new KitDaysApi(configuration);
    this.leaveManagement = new LeaveManagementApi(configuration);
    this.offboarding = new OffboardingApi(configuration);
    this.onboarding = new OnboardingApi(configuration);
    this.performance = new PerformanceApi(configuration);
    this.policies = new PoliciesApi(configuration);
    this.positions = new PositionsApi(configuration);
    this.recruitment = new RecruitmentApi(configuration);
    this.teams = new TeamsApi(configuration);
    this.terminationsReasons = new TerminationsReasonsApi(configuration);
    this.timesheets = new TimesheetsApi(configuration);
  }

}
