/* tslint:disable */
/* eslint-disable */
/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { DocumentsCreateNewDocumentRequest } from '../models';
// @ts-ignore
import { DocumentsCreateNewDocumentResponse } from '../models';
// @ts-ignore
import { DocumentsListCategoriesResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * DocumentsApi - axios parameter creator
 * @export
 */
export const DocumentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Document will only be visible to employee themselves
         * @summary Create new document
         * @param {Uint8Array | File | buffer.File} file The file to upload.
         * @param {number} employeeId Employee identifier
         * @param {DocumentsCreateNewDocumentRequest} documentsCreateNewDocumentRequest 
         * @param {string} [description] Document description
         * @param {number} [categoryId] Category identifier, leave empty for default category
         * @param {string} [notify] \\\&#39;true\\\&#39; to notify employee by email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewDocument: async (file: Uint8Array | File | buffer.File, employeeId: number, documentsCreateNewDocumentRequest: DocumentsCreateNewDocumentRequest, description?: string, categoryId?: number, notify?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('createNewDocument', 'file', file)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('createNewDocument', 'employeeId', employeeId)
            // verify required parameter 'documentsCreateNewDocumentRequest' is not null or undefined
            assertParamExists('createNewDocument', 'documentsCreateNewDocumentRequest', documentsCreateNewDocumentRequest)
            const localVarPath = `/documents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            const addFormParam = async (name: string, data: any, isBinary: boolean, isPrimitiveType: boolean) => {
                if (isBinary) {
                    if (data instanceof Uint8Array) {
                        // Handle Buffer data
                        const filetype = await fromBuffer(data)
                        const filename = filetype === undefined ? name : `${name}.${filetype.ext}`
                        localVarFormParams.append(name, data as any, filename);
                    } else if ("name" in data) {
                        // File instances in browsers and Node.js have the
                        // "name" property "Duck typing" files to handle browser
                        // File class or Node.js File class
                        // Web: https://developer.mozilla.org/en-US/docs/Web/API/File
                        // Node.js: https://nodejs.org/api/buffer.html#new-bufferfilesources-filename-options
                        if (isBrowser()) {
                            // FormData in browser can accept File/Blob directly
                            localVarFormParams.append(name, data, data.name);
                        } else {
                            // FormData in Node.js can only accept raw Buffer so convert before passing
                            const bytes = await data.arrayBuffer()
                            const buffer = Buffer.from(bytes)
                            localVarFormParams.append(name, buffer, data.name);
                        }
                    }
                } else {
                    if (isPrimitiveType) {
                        /**
                         * FormData can only accept string or Blob so we need to convert
                         * non-string primitives to string. We also need to convert
                         */
                        if (typeof data === "object") {
                          localVarFormParams.append(name, JSON.stringify(data));
                        } else {
                          localVarFormParams.append(name, data);
                        }
                    } else {
                        if (isBrowser()) {
                            localVarFormParams.append(name, new Blob([JSON.stringify(data)], { type: "application/json" }))
                        } else {
                            localVarFormParams.append(name, JSON.stringify(data), { type: "application/json", filename: "data.json" });
                        }
                    }
                }
            }
            if (!isBrowser()) Object.assign(localVarHeaderParameter, localVarFormParams.getHeaders());


            if (description !== undefined) {
                await addFormParam('description', description, false, true)
            }
    
            if (file !== undefined) {
                await addFormParam('file', file, true, true)
            }
    
            if (employeeId !== undefined) {
                await addFormParam('employee_id', employeeId, false, true)
            }
    
            if (categoryId !== undefined) {
                await addFormParam('category_id', categoryId, false, true)
            }
    
            if (notify !== undefined) {
                await addFormParam('notify', notify, false, true)
            }
    
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;
            requestBeforeHook({
                requestBody: documentsCreateNewDocumentRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/documents',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List document categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCategories: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/documents/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/documents/categories',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentsApi - functional programming interface
 * @export
 */
export const DocumentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DocumentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Document will only be visible to employee themselves
         * @summary Create new document
         * @param {DocumentsApiCreateNewDocumentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewDocument(requestParameters: DocumentsApiCreateNewDocumentRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentsCreateNewDocumentResponse>> {
            const documentsCreateNewDocumentRequest: DocumentsCreateNewDocumentRequest = {
                description: requestParameters.description,
                file: requestParameters.file,
                employee_id: requestParameters.employee_id,
                category_id: requestParameters.category_id,
                notify: requestParameters.notify
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewDocument(requestParameters.file, requestParameters.employeeId, documentsCreateNewDocumentRequest, requestParameters.description, requestParameters.categoryId, requestParameters.notify, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List document categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCategories(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentsListCategoriesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCategories(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DocumentsApi - factory interface
 * @export
 */
export const DocumentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DocumentsApiFp(configuration)
    return {
        /**
         * Document will only be visible to employee themselves
         * @summary Create new document
         * @param {DocumentsApiCreateNewDocumentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewDocument(requestParameters: DocumentsApiCreateNewDocumentRequest, options?: AxiosRequestConfig): AxiosPromise<DocumentsCreateNewDocumentResponse> {
            return localVarFp.createNewDocument(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List document categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCategories(options?: AxiosRequestConfig): AxiosPromise<DocumentsListCategoriesResponse> {
            return localVarFp.listCategories(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createNewDocument operation in DocumentsApi.
 * @export
 * @interface DocumentsApiCreateNewDocumentRequest
 */
export type DocumentsApiCreateNewDocumentRequest = {
    
    /**
    * The file to upload.
    * @type {Uint8Array | File | buffer.File}
    * @memberof DocumentsApiCreateNewDocument
    */
    readonly file: Uint8Array | File | buffer.File
    
    /**
    * Employee identifier
    * @type {number}
    * @memberof DocumentsApiCreateNewDocument
    */
    readonly employeeId: number
    
    /**
    * Document description
    * @type {string}
    * @memberof DocumentsApiCreateNewDocument
    */
    readonly description?: string
    
    /**
    * Category identifier, leave empty for default category
    * @type {number}
    * @memberof DocumentsApiCreateNewDocument
    */
    readonly categoryId?: number
    
    /**
    * \\\'true\\\' to notify employee by email
    * @type {string}
    * @memberof DocumentsApiCreateNewDocument
    */
    readonly notify?: string
    
} & DocumentsCreateNewDocumentRequest

/**
 * DocumentsApiGenerated - object-oriented interface
 * @export
 * @class DocumentsApiGenerated
 * @extends {BaseAPI}
 */
export class DocumentsApiGenerated extends BaseAPI {
    /**
     * Document will only be visible to employee themselves
     * @summary Create new document
     * @param {DocumentsApiCreateNewDocumentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiGenerated
     */
    public createNewDocument(requestParameters: DocumentsApiCreateNewDocumentRequest, options?: AxiosRequestConfig) {
        return DocumentsApiFp(this.configuration).createNewDocument(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List document categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApiGenerated
     */
    public listCategories(options?: AxiosRequestConfig) {
        return DocumentsApiFp(this.configuration).listCategories(options).then((request) => request(this.axios, this.basePath));
    }
}
