/* tslint:disable */
/* eslint-disable */
/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { TerminationsReasonsListInCompanyResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * TerminationsReasonsApi - axios parameter creator
 * @export
 */
export const TerminationsReasonsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List termination reasons in company
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInCompany: async (page?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/termination-reasons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "X-Auth-Token", keyParamName: "apiKey", configuration })
            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/termination-reasons',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TerminationsReasonsApi - functional programming interface
 * @export
 */
export const TerminationsReasonsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TerminationsReasonsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List termination reasons in company
         * @param {TerminationsReasonsApiListInCompanyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listInCompany(requestParameters: TerminationsReasonsApiListInCompanyRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TerminationsReasonsListInCompanyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listInCompany(requestParameters.page, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TerminationsReasonsApi - factory interface
 * @export
 */
export const TerminationsReasonsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TerminationsReasonsApiFp(configuration)
    return {
        /**
         * 
         * @summary List termination reasons in company
         * @param {TerminationsReasonsApiListInCompanyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInCompany(requestParameters: TerminationsReasonsApiListInCompanyRequest = {}, options?: AxiosRequestConfig): AxiosPromise<TerminationsReasonsListInCompanyResponse> {
            return localVarFp.listInCompany(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listInCompany operation in TerminationsReasonsApi.
 * @export
 * @interface TerminationsReasonsApiListInCompanyRequest
 */
export type TerminationsReasonsApiListInCompanyRequest = {
    
    /**
    * 
    * @type {number}
    * @memberof TerminationsReasonsApiListInCompany
    */
    readonly page?: number
    
}

/**
 * TerminationsReasonsApiGenerated - object-oriented interface
 * @export
 * @class TerminationsReasonsApiGenerated
 * @extends {BaseAPI}
 */
export class TerminationsReasonsApiGenerated extends BaseAPI {
    /**
     * 
     * @summary List termination reasons in company
     * @param {TerminationsReasonsApiListInCompanyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TerminationsReasonsApiGenerated
     */
    public listInCompany(requestParameters: TerminationsReasonsApiListInCompanyRequest = {}, options?: AxiosRequestConfig) {
        return TerminationsReasonsApiFp(this.configuration).listInCompany(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
