/* tslint:disable */
/* eslint-disable */
/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { TimesheetsClockInOutRequest } from '../models';
// @ts-ignore
import { TimesheetsClockInOutRequestClockedTime } from '../models';
// @ts-ignore
import { TimesheetsClockInOutResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * TimesheetsApi - axios parameter creator
 * @export
 */
export const TimesheetsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Employees will be only clocked in & out if API time clocking is enabled for Timesheet group
         * @summary Clock in & out employees on specific days
         * @param {TimesheetsClockInOutRequest} timesheetsClockInOutRequest Times on specific dates for specific employees as json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clockInOut: async (timesheetsClockInOutRequest: TimesheetsClockInOutRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'timesheetsClockInOutRequest' is not null or undefined
            assertParamExists('clockInOut', 'timesheetsClockInOutRequest', timesheetsClockInOutRequest)
            const localVarPath = `/timesheets/clock-in`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "X-Auth-Token", keyParamName: "apiKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: timesheetsClockInOutRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/timesheets/clock-in',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(timesheetsClockInOutRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TimesheetsApi - functional programming interface
 * @export
 */
export const TimesheetsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TimesheetsApiAxiosParamCreator(configuration)
    return {
        /**
         * Employees will be only clocked in & out if API time clocking is enabled for Timesheet group
         * @summary Clock in & out employees on specific days
         * @param {TimesheetsApiClockInOutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async clockInOut(requestParameters: TimesheetsApiClockInOutRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetsClockInOutResponse>> {
            const timesheetsClockInOutRequest: TimesheetsClockInOutRequest = {
                override: requestParameters.override,
                clocked_time: requestParameters.clocked_time
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.clockInOut(timesheetsClockInOutRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TimesheetsApi - factory interface
 * @export
 */
export const TimesheetsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TimesheetsApiFp(configuration)
    return {
        /**
         * Employees will be only clocked in & out if API time clocking is enabled for Timesheet group
         * @summary Clock in & out employees on specific days
         * @param {TimesheetsApiClockInOutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clockInOut(requestParameters: TimesheetsApiClockInOutRequest, options?: AxiosRequestConfig): AxiosPromise<TimesheetsClockInOutResponse> {
            return localVarFp.clockInOut(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for clockInOut operation in TimesheetsApi.
 * @export
 * @interface TimesheetsApiClockInOutRequest
 */
export type TimesheetsApiClockInOutRequest = {
    
} & TimesheetsClockInOutRequest

/**
 * TimesheetsApiGenerated - object-oriented interface
 * @export
 * @class TimesheetsApiGenerated
 * @extends {BaseAPI}
 */
export class TimesheetsApiGenerated extends BaseAPI {
    /**
     * Employees will be only clocked in & out if API time clocking is enabled for Timesheet group
     * @summary Clock in & out employees on specific days
     * @param {TimesheetsApiClockInOutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimesheetsApiGenerated
     */
    public clockInOut(requestParameters: TimesheetsApiClockInOutRequest, options?: AxiosRequestConfig) {
        return TimesheetsApiFp(this.configuration).clockInOut(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
