/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentsCreateNewDocumentRequest
 */
export interface DocumentsCreateNewDocumentRequest {
    /**
     * Document description
     * @type {string}
     * @memberof DocumentsCreateNewDocumentRequest
     */
    'description'?: string;
    /**
     * The file to upload.
     * @type {Uint8Array | File | buffer.File}
     * @memberof DocumentsCreateNewDocumentRequest
     */
    'file': Uint8Array | File | buffer.File;
    /**
     * Employee identifier
     * @type {number}
     * @memberof DocumentsCreateNewDocumentRequest
     */
    'employee_id': number;
    /**
     * Category identifier, leave empty for default category
     * @type {number}
     * @memberof DocumentsCreateNewDocumentRequest
     */
    'category_id'?: number;
    /**
     * \'true\' to notify employee by email
     * @type {string}
     * @memberof DocumentsCreateNewDocumentRequest
     */
    'notify'?: string;
}

