/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeUpdateByIdRequest
 */
export interface EmployeeUpdateByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof EmployeeUpdateByIdRequest
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeUpdateByIdRequest
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeUpdateByIdRequest
     */
    'work_start_date'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeUpdateByIdRequest
     */
    'location_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeUpdateByIdRequest
     */
    'team_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeUpdateByIdRequest
     */
    'leader_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeUpdateByIdRequest
     */
    'position_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeUpdateByIdRequest
     */
    'employee_number'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof EmployeeUpdateByIdRequest
     */
    'approver_ids'?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof EmployeeUpdateByIdRequest
     */
    'selected_leave_types'?: Array<number>;
}

