/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeCreateNewEmployeeRequest
 */
export interface EmployeeCreateNewEmployeeRequest {
    /**
     * Employees email
     * @type {string}
     * @memberof EmployeeCreateNewEmployeeRequest
     */
    'email': string;
    /**
     * Employees first name
     * @type {string}
     * @memberof EmployeeCreateNewEmployeeRequest
     */
    'first_name': string;
    /**
     * Employees last name
     * @type {string}
     * @memberof EmployeeCreateNewEmployeeRequest
     */
    'last_name': string;
    /**
     * Employees work start date, format: YYYY-MM-DD, leave empty to use todays date
     * @type {string}
     * @memberof EmployeeCreateNewEmployeeRequest
     */
    'work_start_date'?: string;
    /**
     * \'true\' to send welcome email to employee
     * @type {string}
     * @memberof EmployeeCreateNewEmployeeRequest
     */
    'send_email'?: string;
}

