/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeGetTerminatedEmployeeResponseDataTermination } from './employee-get-terminated-employee-response-data-termination';

/**
 * 
 * @export
 * @interface EmployeeGetTerminatedEmployeeResponseData
 */
export interface EmployeeGetTerminatedEmployeeResponseData {
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'termination_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'picture_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'employment_start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'position'?: string;
    /**
     * 
     * @type {EmployeeGetTerminatedEmployeeResponseDataTermination}
     * @memberof EmployeeGetTerminatedEmployeeResponseData
     */
    'termination'?: EmployeeGetTerminatedEmployeeResponseDataTermination;
}

