/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeGetByIdResponseDataEmploymentStatusHistoryInner } from './employee-get-by-id-response-data-employment-status-history-inner';
import { EmployeeGetByIdResponseDataPositionHistoryInner } from './employee-get-by-id-response-data-position-history-inner';
import { EmployeeGetByIdResponseDataTeamHistoryInner } from './employee-get-by-id-response-data-team-history-inner';

/**
 * 
 * @export
 * @interface EmployeeGetByIdResponseData
 */
export interface EmployeeGetByIdResponseData {
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetByIdResponseData
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'picture_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'employment_start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'team'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetByIdResponseData
     */
    'team_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'position'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetByIdResponseData
     */
    'position_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetByIdResponseData
     */
    'reports_to_employee_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'work_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'home_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'mobile_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'street_first'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'street_second'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'city'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetByIdResponseData
     */
    'post_code'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'employee_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetByIdResponseData
     */
    'employment_status'?: string;
    /**
     * 
     * @type {Array<EmployeeGetByIdResponseDataTeamHistoryInner>}
     * @memberof EmployeeGetByIdResponseData
     */
    'team_history'?: Array<EmployeeGetByIdResponseDataTeamHistoryInner>;
    /**
     * 
     * @type {Array<EmployeeGetByIdResponseDataEmploymentStatusHistoryInner>}
     * @memberof EmployeeGetByIdResponseData
     */
    'employment_status_history'?: Array<EmployeeGetByIdResponseDataEmploymentStatusHistoryInner>;
    /**
     * 
     * @type {Array<EmployeeGetByIdResponseDataPositionHistoryInner>}
     * @memberof EmployeeGetByIdResponseData
     */
    'position_history'?: Array<EmployeeGetByIdResponseDataPositionHistoryInner>;
}

