/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeGetCompensationsResponseDataInner
 */
export interface EmployeeGetCompensationsResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetCompensationsResponseDataInner
     */
    'start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetCompensationsResponseDataInner
     */
    'end_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetCompensationsResponseDataInner
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetCompensationsResponseDataInner
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetCompensationsResponseDataInner
     */
    'period'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetCompensationsResponseDataInner
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetCompensationsResponseDataInner
     */
    'category'?: string;
}

