/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeListTerminatedEmployeesResponseDataInner
 */
export interface EmployeeListTerminatedEmployeesResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'termination_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'employee_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'picture_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'employment_start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeListTerminatedEmployeesResponseDataInner
     */
    'position'?: string;
}

