/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IntegrationsTransferLeaveInformationToVikarinaResponseData
 */
export interface IntegrationsTransferLeaveInformationToVikarinaResponseData {
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferLeaveInformationToVikarinaResponseData
     */
    'calendar_event_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferLeaveInformationToVikarinaResponseData
     */
    'employee_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferLeaveInformationToVikarinaResponseData
     */
    'leave_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferLeaveInformationToVikarinaResponseData
     */
    'days'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferLeaveInformationToVikarinaResponseData
     */
    'start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferLeaveInformationToVikarinaResponseData
     */
    'end_date'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferLeaveInformationToVikarinaResponseData
     */
    'status'?: number;
}

