/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IntegrationsTransferAppointmentInfoResponseData
 */
export interface IntegrationsTransferAppointmentInfoResponseData {
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'employee_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'employee_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'work_start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'position_start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'last_position_end_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'cost_center_code'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'position_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'schedule_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'employment_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'job_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferAppointmentInfoResponseData
     */
    'status'?: number;
}

