/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IntegrationsTransferTerminationInfoToVikarinaResponseData
 */
export interface IntegrationsTransferTerminationInfoToVikarinaResponseData {
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'employee_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'employee_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'contract_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'termination_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'termination_reason'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'unused_days'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'termination_comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'compensation'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTerminationInfoToVikarinaResponseData
     */
    'status'?: number;
}

