/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IntegrationsTransferTimeScheduleInformationResponseData
 */
export interface IntegrationsTransferTimeScheduleInformationResponseData {
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'employee_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'employee_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'date'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'stand_by'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'hours'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'nightours'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'cost_center_code'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'overtime_title'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsTransferTimeScheduleInformationResponseData
     */
    'status'?: number;
}

