/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IntegrationsImportNewStartersListResponseData
 */
export interface IntegrationsImportNewStartersListResponseData {
    /**
     * 
     * @type {number}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'employee_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'employee_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'work_start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'personal_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'social_security_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'home_city'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'country_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'npd'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'email'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsImportNewStartersListResponseData
     */
    'status'?: number;
}

