/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LeaveManagementCreateKitDayRequest
 */
export interface LeaveManagementCreateKitDayRequest {
    /**
     * Time-off policy identifier
     * @type {number}
     * @memberof LeaveManagementCreateKitDayRequest
     */
    'policy_id': number;
    /**
     * Employee identifier
     * @type {number}
     * @memberof LeaveManagementCreateKitDayRequest
     */
    'employee_id': number;
    /**
     * Date of single-day KIT day
     * @type {string}
     * @memberof LeaveManagementCreateKitDayRequest
     */
    'date'?: string;
    /**
     * Start date of a multi-day KIT day
     * @type {string}
     * @memberof LeaveManagementCreateKitDayRequest
     */
    'date_from'?: string;
    /**
     * End date of a multi-day KIT day
     * @type {string}
     * @memberof LeaveManagementCreateKitDayRequest
     */
    'date_to'?: string;
}

