/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LeaveManagementListTimeOffPoliciesResponseDataInner
 */
export interface LeaveManagementListTimeOffPoliciesResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'color'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'do_not_accrue'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'unit'?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'default_allowance'?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'max_carryover'?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    'accrue_type'?: string;
}

