/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee } from './leave-management-list-employees-out-today-response-data-inner-employee';
import { LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy } from './leave-management-list-employees-out-today-response-data-inner-policy';

/**
 * 
 * @export
 * @interface LeaveManagementListEmployeesOutTodayResponseDataInner
 */
export interface LeaveManagementListEmployeesOutTodayResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'policy_id'?: number;
    /**
     * 
     * @type {LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'policy'?: LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy;
    /**
     * 
     * @type {number}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'employee_id'?: number;
    /**
     * 
     * @type {LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'employee'?: LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'details'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'is_multi_date'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'is_single_day'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'is_part_of_day'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'first_part_of_day'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'second_part_of_day'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'end_date'?: string;
    /**
     * 
     * @type {number}
     * @memberof LeaveManagementListEmployeesOutTodayResponseDataInner
     */
    'hours'?: number;
}

