/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OffboardingCreateTaskRequest
 */
export interface OffboardingCreateTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof OffboardingCreateTaskRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof OffboardingCreateTaskRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof OffboardingCreateTaskRequest
     */
    'boarding_task_template_category_id': number;
    /**
     * Due date in days before employee last working day
     * @type {number}
     * @memberof OffboardingCreateTaskRequest
     */
    'due_in': number;
    /**
     * Default: self; leader - direct manager; employee - specific employee via assignee_id
     * @type {string}
     * @memberof OffboardingCreateTaskRequest
     */
    'default_assignee_type'?: OffboardingCreateTaskRequestDefaultAssigneeTypeEnum;
    /**
     * Specific assignee if default_assignee_type is \'employee\'
     * @type {number}
     * @memberof OffboardingCreateTaskRequest
     */
    'assignee_id'?: number;
    /**
     * \'true\' to enabled required attachment
     * @type {string}
     * @memberof OffboardingCreateTaskRequest
     */
    'require_attachment'?: string;
}

type OffboardingCreateTaskRequestDefaultAssigneeTypeEnum = 'self' | 'leader' | 'employee'


