/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PerformanceOverviewQuarterlyProgressResponseDataCompany } from './performance-overview-quarterly-progress-response-data-company';
import { PerformanceOverviewQuarterlyProgressResponseDataIndividual } from './performance-overview-quarterly-progress-response-data-individual';
import { PerformanceOverviewQuarterlyProgressResponseDataTeam } from './performance-overview-quarterly-progress-response-data-team';

/**
 * 
 * @export
 * @interface PerformanceOverviewQuarterlyProgressResponseData
 */
export interface PerformanceOverviewQuarterlyProgressResponseData {
    /**
     * 
     * @type {PerformanceOverviewQuarterlyProgressResponseDataCompany}
     * @memberof PerformanceOverviewQuarterlyProgressResponseData
     */
    'company'?: PerformanceOverviewQuarterlyProgressResponseDataCompany;
    /**
     * 
     * @type {PerformanceOverviewQuarterlyProgressResponseDataIndividual}
     * @memberof PerformanceOverviewQuarterlyProgressResponseData
     */
    'individual'?: PerformanceOverviewQuarterlyProgressResponseDataIndividual;
    /**
     * 
     * @type {PerformanceOverviewQuarterlyProgressResponseDataTeam}
     * @memberof PerformanceOverviewQuarterlyProgressResponseData
     */
    'team'?: PerformanceOverviewQuarterlyProgressResponseDataTeam;
}

