/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RecruitmentCreateApplicantWithReferralRequest
 */
export interface RecruitmentCreateApplicantWithReferralRequest {
    /**
     * \'true\' to send thank you email to applicant
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'send_thank_you_email'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[first_name]': string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[last_name]'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[email]'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[referral]'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[phone_number]'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[source]'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[address]'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[summary]'?: string;
    /**
     * The file to upload.
     * @type {Uint8Array | File | buffer.File}
     * @memberof RecruitmentCreateApplicantWithReferralRequest
     */
    'applicant[attachment]'?: Uint8Array | File | buffer.File;
}

