/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecruitmentGetApplicantDetailsResponseDataAddedBy } from './recruitment-get-applicant-details-response-data-added-by';
import { RecruitmentGetApplicantDetailsResponseDataReferrer } from './recruitment-get-applicant-details-response-data-referrer';
import { RecruitmentGetApplicantDetailsResponseDataStage } from './recruitment-get-applicant-details-response-data-stage';

/**
 * 
 * @export
 * @interface RecruitmentGetApplicantDetailsResponseData
 */
export interface RecruitmentGetApplicantDetailsResponseData {
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'summary'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'phone_number'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'disqualified_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'hired_date'?: string | null;
    /**
     * 
     * @type {RecruitmentGetApplicantDetailsResponseDataStage}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'stage'?: RecruitmentGetApplicantDetailsResponseDataStage;
    /**
     * 
     * @type {number}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'position_id'?: number;
    /**
     * 
     * @type {RecruitmentGetApplicantDetailsResponseDataAddedBy}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'added_by'?: RecruitmentGetApplicantDetailsResponseDataAddedBy;
    /**
     * 
     * @type {RecruitmentGetApplicantDetailsResponseDataReferrer}
     * @memberof RecruitmentGetApplicantDetailsResponseData
     */
    'referrer'?: RecruitmentGetApplicantDetailsResponseDataReferrer;
}

