/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecruitmentListApplicantsResponseDataInnerStage } from './recruitment-list-applicants-response-data-inner-stage';

/**
 * 
 * @export
 * @interface RecruitmentListApplicantsResponseDataInner
 */
export interface RecruitmentListApplicantsResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'summary'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'phone_number'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'disqualified_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'hired_date'?: string | null;
    /**
     * 
     * @type {RecruitmentListApplicantsResponseDataInnerStage}
     * @memberof RecruitmentListApplicantsResponseDataInner
     */
    'stage'?: RecruitmentListApplicantsResponseDataInnerStage;
}

