/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecruitmentListApplicantsResponseDataInner } from './recruitment-list-applicants-response-data-inner';
import { RecruitmentListApplicantsResponseMeta } from './recruitment-list-applicants-response-meta';

/**
 * 
 * @export
 * @interface RecruitmentListApplicantsResponse
 */
export interface RecruitmentListApplicantsResponse {
    /**
     * 
     * @type {Array<RecruitmentListApplicantsResponseDataInner>}
     * @memberof RecruitmentListApplicantsResponse
     */
    'data'?: Array<RecruitmentListApplicantsResponseDataInner>;
    /**
     * 
     * @type {RecruitmentListApplicantsResponseMeta}
     * @memberof RecruitmentListApplicantsResponse
     */
    'meta'?: RecruitmentListApplicantsResponseMeta;
}

