/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TeamsListInCompanyResponseDataInner } from './teams-list-in-company-response-data-inner';
import { TeamsListInCompanyResponseMeta } from './teams-list-in-company-response-meta';

/**
 * 
 * @export
 * @interface TeamsListInCompanyResponse
 */
export interface TeamsListInCompanyResponse {
    /**
     * 
     * @type {Array<TeamsListInCompanyResponseDataInner>}
     * @memberof TeamsListInCompanyResponse
     */
    'data'?: Array<TeamsListInCompanyResponseDataInner>;
    /**
     * 
     * @type {TeamsListInCompanyResponseMeta}
     * @memberof TeamsListInCompanyResponse
     */
    'meta'?: TeamsListInCompanyResponseMeta;
}

