/*
Sage HR API

All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TerminationsReasonsListInCompanyResponseDataInner } from './terminations-reasons-list-in-company-response-data-inner';
import { TerminationsReasonsListInCompanyResponseMeta } from './terminations-reasons-list-in-company-response-meta';

/**
 * 
 * @export
 * @interface TerminationsReasonsListInCompanyResponse
 */
export interface TerminationsReasonsListInCompanyResponse {
    /**
     * 
     * @type {Array<TerminationsReasonsListInCompanyResponseDataInner>}
     * @memberof TerminationsReasonsListInCompanyResponse
     */
    'data'?: Array<TerminationsReasonsListInCompanyResponseDataInner>;
    /**
     * 
     * @type {TerminationsReasonsListInCompanyResponseMeta}
     * @memberof TerminationsReasonsListInCompanyResponse
     */
    'meta'?: TerminationsReasonsListInCompanyResponseMeta;
}

